name: 'relayboard'
version: '0.1.0'
config-version: 2

profile: 'relayboard'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
macro-paths: ['macros']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']

models:
  relayboard:
    +materialized: view
